[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=31F41CF742184B7B9F49620D70A41688
ProjectName=Lighthaven

[/Script/UnrealEd.ProjectPackagingSettings]
+MapsToCook=(FilePath="/Game/Lighthaven/Maps/L_Frontend")
+MapsToCook=(FilePath="/Game/Lighthaven/Maps/Dev_Combat")
+MapsToCook=(FilePath="/Game/Lighthaven/Maps/Dev_Movement")

; Linux packaging target is selected by build/package-linux.sh (-platform=Linux).
